export const FETCH_PRESCRIPTIONS = "FETCH_PRESCRIPTIONS";
export const FETCH_USERS = "FETCH_USERS";


export const FETCH_TOKEN = "FETCH_TOKEN";
export const AUTHENTICATED = "AUTHENTICATED";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const BASE_URL = "http://174.142.6.165:3000";
